# Generated by Django 4.2.4 on 2023-08-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('upload_user', models.IntegerField(default=1)),
                ('degree', models.IntegerField(choices=[(1, '容易'), (2, '普通'), (3, '困难')], default=1)),
                ('comment_id', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('upload_user', models.IntegerField(default=1)),
                ('degree', models.IntegerField(choices=[(1, '容易'), (2, '普通'), (3, '困难')], default=1)),
                ('comment_id', models.JSONField(null=True)),
            ],
        ),
    ]
