# Generated by Django 4.2.4 on 2023-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text_file', models.FileField(upload_to='text/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('upload_user', models.IntegerField(default=1)),
                ('degree', models.IntegerField(choices=[(1, '容易'), (2, '普通'), (3, '困难')], default=1)),
                ('comment_id', models.JSONField(null=True)),
            ],
        ),
    ]
