# Generated by Django 4.2.4 on 2023-09-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manage', '0003_audio_category_text_category_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
