# Generated by Django 4.2.4 on 2024-01-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manage', '0004_audio_description_text_description_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='category_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='text',
            name='category_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='video',
            name='category_id',
            field=models.IntegerField(default=-1),
        ),
    ]
