# Generated by Django 4.2.4 on 2023-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.IntegerField(choices=[(1, 'admin'), (0, 'not_admin')])),
                ('wechat_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('courses', models.CharField(max_length=2000)),
            ],
        ),
    ]
