# Generated by Django 4.2.4 on 2023-08-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('stu_id', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('message_status', models.IntegerField(choices=[(1, '已发送'), (2, '已读'), (3, '撤回')])),
            ],
        ),
        migrations.CreateModel(
            name='Interact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('stu_id', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('message_status', models.IntegerField(choices=[(1, '已发送'), (2, '已读'), (3, '撤回')])),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teachers', models.JSONField()),
                ('students', models.JSONField()),
                ('content', models.CharField(max_length=200)),
                ('create_user', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('send_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
