# Generated by Django 4.2.4 on 2023-09-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200)),
                ('target_user_type', models.IntegerField(choices=[(1, 'teacher'), (0, 'student')])),
                ('target_users', models.CharField(max_length=2000)),
                ('status', models.IntegerField(choices=[(1, '撤回'), (0, '已传达')])),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
