# Generated by Django 4.2.4 on 2023-09-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_req', '0003_alter_notification_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('content', models.TextField(max_length=20000)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_content',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(1, '撤回'), (0, '已传达'), (2, '已读')], default=0),
        ),
    ]
