# Generated by Django 4.2.4 on 2023-09-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_req', '0004_chatcontent_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='new_flag',
            field=models.BooleanField(default=True),
        ),
    ]
