# Generated by Django 4.2.4 on 2023-09-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_student_openid_teacher_openid_teacher_wechat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='wechat_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='wechat_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
