# Generated by Django 4.2.4 on 2023-09-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_alter_teacher_password_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
