# Generated by Django 4.2.4 on 2023-09-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_alter_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nick_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_admin',
            field=models.IntegerField(choices=[(1, 'admin'), (0, 'not_admin')], default=0),
        ),
    ]
